"""Nova migração inicial

Revision ID: b1810fc749a8
Revises: 
Create Date: 2024-11-12 09:45:14.988704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1810fc749a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rastreio_de_patrimonios', schema=None) as batch_op:
        batch_op.drop_column('patrimonio_numero_etiqueta')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=11),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=15),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_index('cpf_UNIQUE')
        batch_op.drop_index('email_UNIQUE')
        batch_op.drop_index('telefone_UNIQUE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('telefone_UNIQUE', ['telefone'], unique=True)
        batch_op.create_index('email_UNIQUE', ['email'], unique=True)
        batch_op.create_index('cpf_UNIQUE', ['cpf'], unique=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)

    with op.batch_alter_table('rastreio_de_patrimonios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patrimonio_numero_etiqueta', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
